spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:3000}/${DB_NAME:ecommerce_inventory}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
     group-id: inventory-service
     auto-offset-reset: earliest
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.type.mapping: orderPlacedEvent:dev.sespinal.inventoryservice.kafka.event.OrderPlacedEvent
      spring.json.trusted.packages: dev.sespinal.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
       spring.json.type.mapping: orderConfirmedEvent:dev.sespinal.inventoryservice.kafka.event.OrderConfirmedEvent,orderCancelledEvent:dev.sespinal.inventoryservice.kafka.event.OrderCancelledEvent
       spring.json.trusted.packages: dev.sespinal.*

server:
  port: 9093

product:
  service:
    url: http://localhost:9090
logging:
  level:
    dev.sespinal.inventoryservice: DEBUG
    org.springframework.web: INFO

